## Vectorized "dot" operators

Every binary operation has a corresponding "dot" operation which does the operation on every element in an array. 
For example, `[1, 2, 3] ^ 3` isn't defined because it's not clear what taking the power of a vector is, but `[1, 2, 3] .^ 3` is defined as cubing each element. 

In [1]:
[1, 2, 3] .^ 3

3-element Array{Int64,1}:
  1
  8
 27

In [3]:
.√ [1, 4, 9]

3-element Array{Float64,1}:
 1.0
 2.0
 3.0

Multiple dot operators combine together so there's only 1 loop over the elements

In [18]:
A = [1,2,3]
2 .* A.^2 + sin.(A) # Does in 1 loop

3-element Array{Float64,1}:
  2.8414709848078967
  8.909297426825681
 18.14112000805987

In [19]:
# The above is equal to 
@. 2A^2 + sin(A)

3-element Array{Float64,1}:
  2.8414709848078967
  8.909297426825681
 18.14112000805987

The dot syntax is also defined for user-defined operators: 

In [22]:
const ⊗ = kron 
# [A, B] .⊗ [C, D] = [A ⊗ C, B ⊗ D]
A = ones(1); B = ones(2); C = ones(3); D = ones(4)

[A, B] .⊗ [C, D]

2-element Array{Array{Float64,1},1}:
 [1.0, 1.0, 1.0]
 [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]

Dot syntax can be confusing with literal numbers so spaces are enforced: 

In [25]:
# 1.+x could mean 1. + x or 1 .+ x
1.+x

LoadError: syntax: invalid syntax "1.+"; add space(s) to clarify

In [28]:
[1, 2, 3] .== [1, 2, 3]

3-element BitArray{1}:
 1
 1
 1

In [32]:
# Use double slashes for fractions
4 // 3

4//3

In [34]:
x = 4
2^2x

256

In [35]:
# Don't need to use * for variable literal multiplication
4x

16

In [39]:
# Imaginary numbers
e^pi*i

UndefVarError: UndefVarError: e not defined